export enum RecommendationType {
    MEMORY = 'MEMORY',
    FLUENCY = 'FLUENCY',
    VISUOSPATIAL = 'VISUOSPATIAL',
    ATTENTION = 'ATTENTION',
    PUZZLE = 'PUZZLE',
    SUDOKU = 'SUDOKU',
    MEDICATION = 'MEDICATION',
    EXERCISE = 'EXERCISE',
    DIET = 'DIET',
    LIFESTYLE = 'LIFESTYLE',
    OTHER = 'OTHER',
}

export enum RecommendationStatus {
    ACTIVE = 'ACTIVE',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    EXPIRED = 'EXPIRED',
}

export enum PatientLevel {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
}

export enum MedicalEventType {
    MEMORY = 'MEMORY',
    FLUENCY = 'FLUENCY',
    VISUOSPATIAL = 'VISUOSPATIAL',
    ATTENTION = 'ATTENTION',
    PUZZLE = 'PUZZLE',
    SUDOKU = 'SUDOKU',
    MEDICATION = 'MEDICATION',
    EXERCISE = 'EXERCISE',
    DIET = 'DIET',
    LIFESTYLE = 'LIFESTYLE',
    OTHER = 'OTHER',
}

export enum MedicalEventStatus {
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}

export enum DifficultyLevel {
    EASY = 'EASY',
    MEDIUM = 'MEDIUM',
    HARD = 'HARD',
}

export enum ParticipantType {
    PATIENT = 'PATIENT',
    FAMILY = 'FAMILY',
}

export interface Recommendation {
    id?: number;
    content: string;
    type: RecommendationType;
    status?: RecommendationStatus;
    dismissed?: boolean;
    priority?: number;
    doctorId: number;
    patientId: number;
    doctorName?: string;
    patientName?: string;
    medicalEvents?: MedicalEvent[];
    expirationDate?: string | null;
    acceptedAt?: string | null;
    generatedMedicalEventId?: number | null;
    generatedMedicalEventTitle?: string | null;
    rejectionCount?: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface RecommendationStats {
    patientId: number;
    acceptedCount: number;
    rejectedCount: number;
}

export interface AutoRecommendationGenerateRequest {
    doctorId: number;
    patientId: number;
    preferredMedicalEventId?: number | null;
    age: number;
    level: PatientLevel;
    weeklyFrequency: number;
    acceptedCount: number;
    rejectedCount: number;
    medicationAdherenceIssue: boolean;
    lowPhysicalActivity: boolean;
    cognitiveDropObserved: boolean;
    recentRecommendationTypes: RecommendationType[];
}

export interface ClinicalEscalationAlert {
    id: number;
    recommendationId: number;
    doctorId: number;
    patientId: number;
    recommendationType: RecommendationType;
    rejectionCount: number;
    message: string;
    status: 'OPEN' | 'RESOLVED';
    createdAt: string;
    updatedAt: string;
}

export interface MedicalEvent {
    id?: number;
    title: string;
    description?: string;
    type: MedicalEventType;
    difficulty: DifficultyLevel;
    status?: MedicalEventStatus;
    patientId?: number;
    familyId?: number | null;
    startDate?: string;
    endDate?: string;
    autoGenerated?: boolean;
    participationCount?: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface JoinMedicalEventRequest {
    participantId: number;
    participantType: ParticipantType;
    participationDate?: string;
    score?: number;
}

export interface MedicalEventParticipation {
    id: number;
    medicalEventId: number;
    participantId: number;
    participantType: ParticipantType;
    participationDate: string;
    score: number;
    createdAt: string;
}

export interface StreakResponse {
    medicalEventId: number;
    participantId: number;
    streakDays: number;
}

export interface ScoreResponse {
    medicalEventId: number;
    participantId: number;
    totalScore: number;
}

export interface ParticipantRanking {
    participantId: number;
    participantType: ParticipantType;
    totalScore: number;
    participations: number;
    rank: number;
}

export enum PuzzleStatus {
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    ARCHIVED = 'ARCHIVED',
}

export interface SouvenirSourceSummary {
    id: number;
    patientId: number;
    mediaType: string;
    mediaUrl: string;
    mediaTitle: string;
    texte: string;
}

export interface PuzzleCreateRequest {
    souvenirEntryId: number;
    patientId: number;
    title?: string | null;
    description?: string | null;
    difficulty: DifficultyLevel;
    timeLimitSeconds?: number | null;
    maxHints?: number | null;
    startDate?: string | null;
    endDate?: string | null;
}

export interface Puzzle {
    id: number;
    medicalEventId: number;
    souvenirEntryId: number;
    patientId: number;
    title: string;
    description: string;
    difficulty: DifficultyLevel;
    gridSize: number;
    timeLimitSeconds: number;
    maxHints: number;
    status: PuzzleStatus;
    bestScore?: number | null;
    completedSessions?: number | null;
    createdAt?: string;
    updatedAt?: string;
    souvenir: SouvenirSourceSummary;
}

export interface PuzzleLeaderboardEntry {
    rank: number;
    patientId: number;
    bestScore: number;
    bestDurationSeconds?: number | null;
    completedSessions?: number | null;
    lastCompletedAt?: string | null;
}

export interface PuzzleSession {
    id: number;
    puzzleId: number;
    patientId: number;
    startedAt: string;
    finishedAt?: string | null;
    durationSeconds?: number | null;
    movesCount?: number | null;
    errorsCount?: number | null;
    hintsUsed?: number | null;
    completionPercent?: number | null;
    score?: number | null;
    completed: boolean;
    abandoned: boolean;
    createdAt?: string;
}

export interface PuzzleSessionStartResponse {
    sessionId: number;
    puzzleId: number;
    patientId: number;
    startedAt: string;
}

export interface PuzzleSessionSubmitRequest {
    patientId: number;
    durationSeconds?: number;
    movesCount?: number;
    errorsCount?: number;
    hintsUsed?: number;
    completionPercent?: number;
    completed: boolean;
    abandoned: boolean;
}

export interface SudokuGame {
    id: number;
    medicalEventId: number;
    patientId: number;
    difficulty: DifficultyLevel;
    gridSize: number;
    puzzle: string; // JSON string "[[1,2,0,4],...]"
    timeLimitSeconds: number;
    active: boolean;
    bestScore?: number | null;
    completedSessions?: number | null;
    createdAt?: string;
}

export interface SudokuSessionStartResponse {
    sessionId: number;
    gameId: number;
    patientId: number;
    startedAt: string;
}

export interface SudokuSessionSubmitRequest {
    patientId: number;
    durationSeconds?: number;
    errorsCount?: number;
    hintsUsed?: number;
    completionPercent?: number;
    completed: boolean;
    abandoned: boolean;
}

export interface SudokuSessionResponse {
    id: number;
    gameId: number;
    patientId: number;
    startedAt: string;
    finishedAt?: string | null;
    durationSeconds?: number | null;
    errorsCount?: number | null;
    hintsUsed?: number | null;
    completionPercent?: number | null;
    score?: number | null;
    completed: boolean;
    abandoned: boolean;
}
