export enum RecommendationType {
    MEMORY = 'MEMORY',
    FLUENCY = 'FLUENCY',
    VISUOSPATIAL = 'VISUOSPATIAL',
    ATTENTION = 'ATTENTION',
    MEDICATION = 'MEDICATION',
    EXERCISE = 'EXERCISE',
    DIET = 'DIET',
    LIFESTYLE = 'LIFESTYLE',
    OTHER = 'OTHER',
}

export enum RecommendationStatus {
    ACTIVE = 'ACTIVE',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    EXPIRED = 'EXPIRED',
}

export enum PatientLevel {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
}

export enum MedicalEventType {
    MEMORY = 'MEMORY',
    FLUENCY = 'FLUENCY',
    VISUOSPATIAL = 'VISUOSPATIAL',
    ATTENTION = 'ATTENTION',
    MEDICATION = 'MEDICATION',
    EXERCISE = 'EXERCISE',
    DIET = 'DIET',
    LIFESTYLE = 'LIFESTYLE',
    OTHER = 'OTHER',
}

export enum MedicalEventStatus {
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
}

export enum DifficultyLevel {
    EASY = 'EASY',
    MEDIUM = 'MEDIUM',
    HARD = 'HARD',
}

export enum ParticipantType {
    PATIENT = 'PATIENT',
    FAMILY = 'FAMILY',
}

export interface Recommendation {
    id?: number;
    content: string;
    type: RecommendationType;
    status?: RecommendationStatus;
    dismissed?: boolean;
    priority?: number;
    doctorId: number;
    patientId: number;
    doctorName?: string;
    patientName?: string;
    medicalEvents?: MedicalEvent[];
    expirationDate?: string | null;
    acceptedAt?: string | null;
    generatedMedicalEventId?: number | null;
    generatedMedicalEventTitle?: string | null;
    rejectionCount?: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface RecommendationStats {
    patientId: number;
    acceptedCount: number;
    rejectedCount: number;
}

export interface AutoRecommendationGenerateRequest {
    doctorId: number;
    patientId: number;
    preferredMedicalEventId?: number | null;
    age: number;
    level: PatientLevel;
    weeklyFrequency: number;
    acceptedCount: number;
    rejectedCount: number;
    medicationAdherenceIssue: boolean;
    lowPhysicalActivity: boolean;
    cognitiveDropObserved: boolean;
    recentRecommendationTypes: RecommendationType[];
}

export interface ClinicalEscalationAlert {
    id: number;
    recommendationId: number;
    doctorId: number;
    patientId: number;
    recommendationType: RecommendationType;
    rejectionCount: number;
    message: string;
    status: 'OPEN' | 'RESOLVED';
    createdAt: string;
    updatedAt: string;
}

export interface MedicalEvent {
    id?: number;
    title: string;
    description?: string;
    type: MedicalEventType;
    difficulty: DifficultyLevel;
    status?: MedicalEventStatus;
    patientId?: number;
    familyId?: number | null;
    startDate?: string;
    endDate?: string;
    autoGenerated?: boolean;
    participationCount?: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface JoinMedicalEventRequest {
    participantId: number;
    participantType: ParticipantType;
    participationDate?: string;
    score?: number;
}

export interface MedicalEventParticipation {
    id: number;
    medicalEventId: number;
    participantId: number;
    participantType: ParticipantType;
    participationDate: string;
    score: number;
    createdAt: string;
}

export interface StreakResponse {
    medicalEventId: number;
    participantId: number;
    streakDays: number;
}

export interface ScoreResponse {
    medicalEventId: number;
    participantId: number;
    totalScore: number;
}

export interface ParticipantRanking {
    participantId: number;
    participantType: ParticipantType;
    totalScore: number;
    participations: number;
    rank: number;
}
