package tn.esprit.recommendation_service.service;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleCreateRequest;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleLeaderboardEntry;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleResponse;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionResponse;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionStartResponse;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionSubmitRequest;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleUpdateRequest;
import tn.esprit.recommendation_service.dto.puzzle.SouvenirSourceSummary;
import tn.esprit.recommendation_service.entity.MedicalEvent;
import tn.esprit.recommendation_service.entity.MedicalEventParticipation;
import tn.esprit.recommendation_service.entity.PuzzleSession;
import tn.esprit.recommendation_service.entity.SouvenirPuzzle;
import tn.esprit.recommendation_service.enums.DifficultyLevel;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;
import tn.esprit.recommendation_service.enums.ParticipantType;
import tn.esprit.recommendation_service.enums.PuzzleStatus;
import tn.esprit.recommendation_service.exception.BusinessException;
import tn.esprit.recommendation_service.exception.ResourceNotFoundException;
import tn.esprit.recommendation_service.repository.MedicalEventParticipationRepository;
import tn.esprit.recommendation_service.repository.MedicalEventRepository;
import tn.esprit.recommendation_service.repository.PuzzleSessionRepository;
import tn.esprit.recommendation_service.repository.SouvenirPuzzleRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
@Transactional
public class SouvenirPuzzleService {

    private final SouvenirPuzzleRepository souvenirPuzzleRepository;
    private final PuzzleSessionRepository puzzleSessionRepository;
    private final MedicalEventRepository medicalEventRepository;
    private final MedicalEventParticipationRepository participationRepository;
    private final PatientStatsService patientStatsService;
    private final RestTemplate restTemplate;

    @Value("${app.souvenir-service.base-url:http://localhost:8086}")
    private String souvenirServiceBaseUrl;

    public PuzzleResponse createPuzzle(PuzzleCreateRequest request) {
        if (souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(request.getSouvenirEntryId(), request.getPatientId())) {
            throw new BusinessException("A puzzle already exists for this souvenir and patient.");
        }

        SouvenirSourceSummary souvenir = validateSource(request.getSouvenirEntryId(), request.getPatientId());
        DifficultyLevel difficulty = request.getDifficulty();

        LocalDateTime startDate = request.getStartDate() != null ? request.getStartDate() : LocalDateTime.now();
        LocalDateTime endDate = request.getEndDate() != null ? request.getEndDate() : startDate.plusDays(7);
        if (!endDate.isAfter(startDate)) {
            throw new BusinessException("Puzzle endDate must be after startDate.");
        }

        MedicalEvent event = medicalEventRepository.save(MedicalEvent.builder()
                .title(resolveTitle(request.getTitle(), souvenir))
                .description(resolveDescription(request.getDescription(), souvenir))
                .type(MedicalEventType.PUZZLE)
                .difficulty(difficulty)
                .status(MedicalEventStatus.ACTIVE)
                .patientId(request.getPatientId())
                .startDate(startDate)
                .endDate(endDate)
                .autoGenerated(Boolean.FALSE)
                .build());

        SouvenirPuzzle puzzle = SouvenirPuzzle.builder()
                .medicalEvent(event)
                .souvenirEntryId(request.getSouvenirEntryId())
                .patientId(request.getPatientId())
                .title(event.getTitle())
                .description(event.getDescription())
                .difficulty(difficulty)
                .gridSize(gridSizeFor(difficulty))
                .timeLimitSeconds(defaultIfNull(request.getTimeLimitSeconds(), 300))
                .maxHints(defaultIfNull(request.getMaxHints(), 3))
                .status(PuzzleStatus.ACTIVE)
                .build();

        return toResponse(souvenirPuzzleRepository.save(puzzle), souvenir);
    }

    public PuzzleResponse getPuzzleById(Long puzzleId) {
        SouvenirPuzzle puzzle = getPuzzleOrThrow(puzzleId);
        return toResponse(refreshPuzzleStatusIfSourceUnavailable(puzzle));
    }

    public List<PuzzleResponse> getPuzzlesByPatient(Long patientId) {
        return souvenirPuzzleRepository.findByPatientIdOrderByCreatedAtDesc(patientId).stream()
                .map(this::refreshPuzzleStatusIfSourceUnavailable)
                .map(this::toResponse)
                .toList();
    }

    public PuzzleResponse getPuzzleByMedicalEvent(Long medicalEventId) {
        SouvenirPuzzle puzzle = souvenirPuzzleRepository.findByMedicalEvent_Id(medicalEventId)
                .orElseThrow(() -> new ResourceNotFoundException("Puzzle not found for MedicalEvent: " + medicalEventId));
        return toResponse(refreshPuzzleStatusIfSourceUnavailable(puzzle));
    }

    public PuzzleResponse updatePuzzle(Long puzzleId, PuzzleUpdateRequest request) {
        SouvenirPuzzle puzzle = getPuzzleOrThrow(puzzleId);
        puzzle.setTitle(request.getTitle().trim());
        puzzle.setDescription(request.getDescription());
        puzzle.setDifficulty(request.getDifficulty());
        puzzle.setGridSize(gridSizeFor(request.getDifficulty()));
        puzzle.setTimeLimitSeconds(defaultIfNull(request.getTimeLimitSeconds(), puzzle.getTimeLimitSeconds()));
        puzzle.setMaxHints(defaultIfNull(request.getMaxHints(), puzzle.getMaxHints()));
        puzzle.setStatus(request.getStatus());

        MedicalEvent event = puzzle.getMedicalEvent();
        event.setTitle(puzzle.getTitle());
        event.setDescription(puzzle.getDescription());
        event.setDifficulty(puzzle.getDifficulty());
        event.setStatus(request.getStatus() == PuzzleStatus.ACTIVE ? MedicalEventStatus.ACTIVE : MedicalEventStatus.CANCELLED);
        medicalEventRepository.save(event);

        return toResponse(souvenirPuzzleRepository.save(puzzle));
    }

    public void deletePuzzle(Long puzzleId) {
        SouvenirPuzzle puzzle = getPuzzleOrThrow(puzzleId);
        puzzle.setStatus(PuzzleStatus.INACTIVE);
        puzzle.getMedicalEvent().setStatus(MedicalEventStatus.CANCELLED);
        medicalEventRepository.save(puzzle.getMedicalEvent());
        souvenirPuzzleRepository.save(puzzle);
    }

    public PuzzleSessionStartResponse startSession(Long puzzleId, Long patientId) {
        SouvenirPuzzle puzzle = refreshPuzzleStatusIfSourceUnavailable(getPuzzleOrThrow(puzzleId));
        ensurePuzzlePlayable(puzzle, patientId);

        PuzzleSession session = puzzleSessionRepository.save(PuzzleSession.builder()
                .puzzle(puzzle)
                .patientId(patientId)
                .startedAt(LocalDateTime.now())
                .build());

        return PuzzleSessionStartResponse.builder()
                .sessionId(session.getId())
                .puzzleId(puzzleId)
                .patientId(patientId)
                .startedAt(session.getStartedAt())
                .build();
    }

    public PuzzleSessionResponse submitSession(Long puzzleId, Long sessionId, PuzzleSessionSubmitRequest request) {
        SouvenirPuzzle puzzle = refreshPuzzleStatusIfSourceUnavailable(getPuzzleOrThrow(puzzleId));
        PuzzleSession session = puzzleSessionRepository.findById(sessionId)
                .orElseThrow(() -> new ResourceNotFoundException("Puzzle session not found: " + sessionId));

        if (!session.getPuzzle().getId().equals(puzzle.getId())) {
            throw new BusinessException("Puzzle session does not belong to the requested puzzle.");
        }
        if (!session.getPatientId().equals(request.getPatientId())) {
            throw new BusinessException("Puzzle session patient does not match.");
        }
        if (session.getFinishedAt() != null) {
            throw new BusinessException("Puzzle session has already been submitted.");
        }

        int duration = defaultIfNull(request.getDurationSeconds(), 0);
        int moves = defaultIfNull(request.getMovesCount(), 0);
        int errors = defaultIfNull(request.getErrorsCount(), 0);
        int hints = defaultIfNull(request.getHintsUsed(), 0);
        int completionPercent = defaultIfNull(request.getCompletionPercent(), 0);
        boolean completed = Boolean.TRUE.equals(request.getCompleted()) && completionPercent >= 100;

        session.setFinishedAt(LocalDateTime.now());
        session.setDurationSeconds(duration);
        session.setMovesCount(moves);
        session.setErrorsCount(errors);
        session.setHintsUsed(hints);
        session.setCompletionPercent(Math.min(completionPercent, 100));
        session.setCompleted(completed);
        session.setAbandoned(Boolean.TRUE.equals(request.getAbandoned()));
        session.setScore(calculateScore(puzzle, duration, moves, errors, hints, completed));

        PuzzleSession saved = puzzleSessionRepository.save(session);
        registerParticipationIfNeeded(puzzle, saved);
        patientStatsService.recordSessionResult(saved);
        return toSessionResponse(saved);
    }

    @Transactional(readOnly = true)
    public List<PuzzleSessionResponse> getSessionsByPatient(Long puzzleId, Long patientId) {
        getPuzzleOrThrow(puzzleId);
        return puzzleSessionRepository.findByPuzzle_IdAndPatientIdOrderByStartedAtDesc(puzzleId, patientId).stream()
                .map(this::toSessionResponse)
                .toList();
    }

    @Transactional(readOnly = true)
    public List<PuzzleLeaderboardEntry> getLeaderboard(Long puzzleId) {
        getPuzzleOrThrow(puzzleId);
        List<PuzzleSession> completedSessions = puzzleSessionRepository
                .findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(puzzleId);

        Map<Long, List<PuzzleSession>> byPatient = new LinkedHashMap<>();
        for (PuzzleSession session : completedSessions) {
            byPatient.computeIfAbsent(session.getPatientId(), key -> new ArrayList<>()).add(session);
        }

        List<PuzzleLeaderboardEntry> leaderboard = new ArrayList<>();
        for (Map.Entry<Long, List<PuzzleSession>> entry : byPatient.entrySet()) {
            List<PuzzleSession> sessions = entry.getValue();
            PuzzleSession best = sessions.get(0);
            leaderboard.add(PuzzleLeaderboardEntry.builder()
                    .patientId(entry.getKey())
                    .bestScore(best.getScore())
                    .bestDurationSeconds(best.getDurationSeconds())
                    .completedSessions(sessions.size())
                    .lastCompletedAt(sessions.stream()
                            .map(PuzzleSession::getFinishedAt)
                            .filter(java.util.Objects::nonNull)
                            .max(LocalDateTime::compareTo)
                            .orElse(best.getFinishedAt()))
                    .build());
        }

        leaderboard.sort(Comparator
                .comparing(PuzzleLeaderboardEntry::getBestScore, Comparator.nullsLast(Comparator.reverseOrder()))
                .thenComparing(PuzzleLeaderboardEntry::getBestDurationSeconds, Comparator.nullsLast(Comparator.naturalOrder()))
                .thenComparing(PuzzleLeaderboardEntry::getLastCompletedAt, Comparator.nullsLast(Comparator.naturalOrder())));

        int rank = 1;
        for (PuzzleLeaderboardEntry entry : leaderboard) {
            entry.setRank(rank++);
        }
        return leaderboard;
    }

    private SouvenirPuzzle getPuzzleOrThrow(Long puzzleId) {
        return souvenirPuzzleRepository.findById(puzzleId)
                .orElseThrow(() -> new ResourceNotFoundException("Puzzle not found: " + puzzleId));
    }

    private SouvenirPuzzle refreshPuzzleStatusIfSourceUnavailable(SouvenirPuzzle puzzle) {
        if (puzzle.getStatus() == PuzzleStatus.INACTIVE) {
            return puzzle;
        }
        try {
            validateSource(puzzle.getSouvenirEntryId(), puzzle.getPatientId());
            return puzzle;
        } catch (BusinessException ex) {
            if ("Unable to validate souvenir source right now.".equals(ex.getMessage())) {
                return puzzle;
            }
            puzzle.setStatus(PuzzleStatus.INACTIVE);
            puzzle.getMedicalEvent().setStatus(MedicalEventStatus.CANCELLED);
            medicalEventRepository.save(puzzle.getMedicalEvent());
            return souvenirPuzzleRepository.save(puzzle);
        } catch (ResourceNotFoundException ex) {
            puzzle.setStatus(PuzzleStatus.INACTIVE);
            puzzle.getMedicalEvent().setStatus(MedicalEventStatus.CANCELLED);
            medicalEventRepository.save(puzzle.getMedicalEvent());
            return souvenirPuzzleRepository.save(puzzle);
        }
    }

    private void ensurePuzzlePlayable(SouvenirPuzzle puzzle, Long patientId) {
        if (!puzzle.getPatientId().equals(patientId)) {
            throw new BusinessException("Puzzle does not belong to the requested patient.");
        }
        if (puzzle.getStatus() != PuzzleStatus.ACTIVE) {
            throw new BusinessException("Puzzle is inactive and cannot be played.");
        }
    }

    private void registerParticipationIfNeeded(SouvenirPuzzle puzzle, PuzzleSession session) {
        if (!Boolean.TRUE.equals(session.getCompleted()) || session.getCompletionPercent() < 100) {
            return;
        }

        LocalDate participationDate = session.getFinishedAt() != null
                ? session.getFinishedAt().toLocalDate()
                : LocalDate.now();

        boolean alreadyTracked = participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantTypeAndParticipationDate(
                puzzle.getMedicalEvent().getId(),
                session.getPatientId(),
                ParticipantType.PATIENT,
                participationDate
        );

        if (alreadyTracked) {
            return;
        }

        participationRepository.save(MedicalEventParticipation.builder()
                .medicalEvent(puzzle.getMedicalEvent())
                .participantId(session.getPatientId())
                .participantType(ParticipantType.PATIENT)
                .participationDate(participationDate)
                .score(session.getScore() == null ? 0 : session.getScore())
                .build());
    }

    private SouvenirSourceSummary validateSource(Long souvenirEntryId, Long patientId) {
        try {
            SouvenirSourceSummary summary = restTemplate.getForObject(
                    souvenirServiceBaseUrl + "/api/souvenirs/" + souvenirEntryId,
                    SouvenirSourceSummary.class
            );

            if (summary == null) {
                throw new ResourceNotFoundException("Souvenir source not found: " + souvenirEntryId);
            }
            if (!patientId.equals(summary.getPatientId())) {
                throw new BusinessException("Souvenir source must belong to the same patient.");
            }
            if (!"IMAGE".equalsIgnoreCase(summary.getMediaType())) {
                throw new BusinessException("Only IMAGE souvenirs can be used for puzzles.");
            }
            if (summary.getMediaUrl() == null || summary.getMediaUrl().isBlank()) {
                throw new BusinessException("Souvenir source must contain a usable mediaUrl.");
            }
            return summary;
        } catch (HttpClientErrorException.NotFound ex) {
            throw new ResourceNotFoundException("Souvenir source not found: " + souvenirEntryId);
        } catch (HttpClientErrorException ex) {
            if (ex.getStatusCode() == HttpStatus.NOT_FOUND) {
                throw new ResourceNotFoundException("Souvenir source not found: " + souvenirEntryId);
            }
            throw new BusinessException("Unable to validate souvenir source right now.");
        }
    }

    private int gridSizeFor(DifficultyLevel difficulty) {
        return switch (difficulty) {
            case EASY -> 3;
            case MEDIUM -> 4;
            case HARD -> 5;
        };
    }

    private int calculateScore(SouvenirPuzzle puzzle, int durationSeconds, int movesCount, int errorsCount, int hintsUsed, boolean completed) {
        int base = 100;
        int minimumExpectedMoves = puzzle.getGridSize() * puzzle.getGridSize();
        int extraMovesPenalty = Math.max(0, movesCount - minimumExpectedMoves);
        int errorsPenalty = Math.max(0, errorsCount) * 2;
        int hintsPenalty = hintsUsed * 5;
        int timeoutPenalty = durationSeconds > puzzle.getTimeLimitSeconds() ? 10 : 0;
        int bonus = completed && hintsUsed == 0 ? 10 : 0;
        return Math.max(0, base - extraMovesPenalty - errorsPenalty - hintsPenalty - timeoutPenalty + bonus);
    }

    private PuzzleResponse toResponse(SouvenirPuzzle puzzle) {
        return toResponse(puzzle, loadSouvenirSummary(puzzle));
    }

    private PuzzleResponse toResponse(SouvenirPuzzle puzzle, SouvenirSourceSummary souvenir) {
        List<PuzzleSession> completedSessions = puzzleSessionRepository
                .findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(puzzle.getId());
        Integer bestScore = completedSessions.isEmpty() ? null : completedSessions.get(0).getScore();

        return PuzzleResponse.builder()
                .id(puzzle.getId())
                .medicalEventId(puzzle.getMedicalEvent().getId())
                .souvenirEntryId(puzzle.getSouvenirEntryId())
                .patientId(puzzle.getPatientId())
                .title(puzzle.getTitle())
                .description(puzzle.getDescription())
                .difficulty(puzzle.getDifficulty())
                .gridSize(puzzle.getGridSize())
                .timeLimitSeconds(puzzle.getTimeLimitSeconds())
                .maxHints(puzzle.getMaxHints())
                .status(puzzle.getStatus())
                .bestScore(bestScore)
                .completedSessions(completedSessions.size())
                .createdAt(puzzle.getCreatedAt())
                .updatedAt(puzzle.getUpdatedAt())
                .souvenir(souvenir)
                .build();
    }

    private PuzzleSessionResponse toSessionResponse(PuzzleSession session) {
        return PuzzleSessionResponse.builder()
                .id(session.getId())
                .puzzleId(session.getPuzzle().getId())
                .patientId(session.getPatientId())
                .startedAt(session.getStartedAt())
                .finishedAt(session.getFinishedAt())
                .durationSeconds(session.getDurationSeconds())
                .movesCount(session.getMovesCount())
                .errorsCount(session.getErrorsCount())
                .hintsUsed(session.getHintsUsed())
                .completionPercent(session.getCompletionPercent())
                .score(session.getScore())
                .completed(session.getCompleted())
                .abandoned(session.getAbandoned())
                .createdAt(session.getCreatedAt())
                .build();
    }

    private SouvenirSourceSummary loadSouvenirSummary(SouvenirPuzzle puzzle) {
        try {
            return validateSource(puzzle.getSouvenirEntryId(), puzzle.getPatientId());
        } catch (RuntimeException ex) {
            return SouvenirSourceSummary.builder()
                    .id(puzzle.getSouvenirEntryId())
                    .patientId(puzzle.getPatientId())
                    .mediaType("IMAGE")
                    .mediaTitle(puzzle.getTitle())
                    .build();
        }
    }

    private String resolveTitle(String requestedTitle, SouvenirSourceSummary souvenir) {
        if (requestedTitle != null && !requestedTitle.isBlank()) {
            return requestedTitle.trim();
        }
        if (souvenir.getMediaTitle() != null && !souvenir.getMediaTitle().isBlank()) {
            return "Puzzle - " + souvenir.getMediaTitle().trim();
        }
        return "Puzzle Souvenir";
    }

    private String resolveDescription(String requestedDescription, SouvenirSourceSummary souvenir) {
        if (requestedDescription != null && !requestedDescription.isBlank()) {
            return requestedDescription.trim();
        }
        if (souvenir.getTexte() != null && !souvenir.getTexte().isBlank()) {
            return "Puzzle therapeutique genere a partir du souvenir: " + souvenir.getTexte().trim();
        }
        return "Puzzle therapeutique base sur un souvenir image du patient.";
    }

    private int defaultIfNull(Integer value, Integer fallback) {
        return value == null ? fallback : value;
    }
}
