package tn.esprit.recommendation_service.service;

import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tn.esprit.recommendation_service.dto.medicalevent.JoinMedicalEventRequest;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventCreateRequest;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventParticipationResponse;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventResponse;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventUpdateRequest;
import tn.esprit.recommendation_service.dto.medicalevent.ParticipantRankingResponse;
import tn.esprit.recommendation_service.dto.medicalevent.ScoreResponse;
import tn.esprit.recommendation_service.dto.medicalevent.StreakResponse;
import tn.esprit.recommendation_service.entity.MedicalEvent;
import tn.esprit.recommendation_service.entity.MedicalEventParticipation;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;
import tn.esprit.recommendation_service.enums.ParticipantType;
import tn.esprit.recommendation_service.exception.BusinessException;
import tn.esprit.recommendation_service.exception.ResourceNotFoundException;
import tn.esprit.recommendation_service.repository.MedicalEventParticipationRepository;
import tn.esprit.recommendation_service.repository.MedicalEventRepository;
import tn.esprit.recommendation_service.repository.projection.ParticipantRankingProjection;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class MedicalEventService {

    private final MedicalEventRepository medicalEventRepository;
    private final MedicalEventParticipationRepository participationRepository;

    public MedicalEventResponse createMedicalEvent(MedicalEventCreateRequest request) {
        validateDateRange(request.getStartDate(), request.getEndDate());

        MedicalEvent medicalEvent = MedicalEvent.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .type(request.getType())
                .difficulty(request.getDifficulty())
                .status(MedicalEventStatus.ACTIVE)
                .patientId(request.getPatientId())
                .familyId(request.getFamilyId())
                .startDate(request.getStartDate())
                .endDate(request.getEndDate())
                .autoGenerated(Boolean.FALSE)
                .build();

        return toResponse(medicalEventRepository.save(medicalEvent));
    }

    @Transactional(readOnly = true)
    public List<MedicalEventResponse> getAllMedicalEvents() {
        return medicalEventRepository.findAll().stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public List<MedicalEventResponse> searchMedicalEvents(String query) {
        return medicalEventRepository.findByTitleContainingIgnoreCaseOrDescriptionContainingIgnoreCase(query, query)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Transactional(readOnly = true)
    public MedicalEventResponse getMedicalEventById(Long eventId) {
        return toResponse(getEventOrThrow(eventId));
    }

    @Transactional(readOnly = true)
    public List<MedicalEventResponse> getActiveMedicalEventsByPatient(Long patientId) {
        return medicalEventRepository.findByPatientIdAndStatusOrderByCreatedAtDesc(patientId, MedicalEventStatus.ACTIVE)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Transactional(readOnly = true)
    public List<MedicalEventResponse> getMedicalEventsByType(MedicalEventType type) {
        return medicalEventRepository.findByTypeOrderByCreatedAtDesc(type)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Transactional(readOnly = true)
    public List<MedicalEventResponse> getCompletedMedicalEvents(Long patientId) {
        return medicalEventRepository.findByPatientIdAndStatusOrderByEndDateDesc(patientId, MedicalEventStatus.COMPLETED)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    public MedicalEventResponse updateMedicalEvent(Long eventId, MedicalEventUpdateRequest request) {
        MedicalEvent event = getEventOrThrow(eventId);
        validateDateRange(request.getStartDate(), request.getEndDate());

        event.setTitle(request.getTitle());
        event.setDescription(request.getDescription());
        event.setType(request.getType());
        event.setDifficulty(request.getDifficulty());
        event.setStatus(request.getStatus());
        event.setPatientId(request.getPatientId());
        event.setFamilyId(request.getFamilyId());
        event.setStartDate(request.getStartDate());
        event.setEndDate(request.getEndDate());

        return toResponse(medicalEventRepository.save(event));
    }

    public void deleteMedicalEvent(Long eventId) {
        MedicalEvent event = getEventOrThrow(eventId);
        if (!LocalDateTime.now().isBefore(event.getStartDate())) {
            throw new BusinessException("MedicalEvent can be deleted only before it starts.");
        }
        medicalEventRepository.delete(event);
    }

    public MedicalEventParticipationResponse joinMedicalEvent(Long eventId, JoinMedicalEventRequest request) {
        MedicalEvent event = getEventOrThrow(eventId);
        if (event.getStatus() != MedicalEventStatus.ACTIVE) {
            throw new BusinessException("Cannot join a non-active MedicalEvent.");
        }

        LocalDate participationDate = request.getParticipationDate() == null ? LocalDate.now() : request.getParticipationDate();

        if (participationDate.isBefore(event.getStartDate().toLocalDate())
                || participationDate.isAfter(event.getEndDate().toLocalDate())) {
            throw new BusinessException("Participation date must be between startDate and endDate.");
        }

        boolean alreadyJoinedToday = participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantTypeAndParticipationDate(
                eventId,
                request.getParticipantId(),
                request.getParticipantType(),
                participationDate
        );

        if (alreadyJoinedToday) {
            throw new BusinessException("Participant already joined this MedicalEvent for the same day.");
        }

        MedicalEventParticipation participation = MedicalEventParticipation.builder()
                .medicalEvent(event)
                .participantId(request.getParticipantId())
                .participantType(request.getParticipantType())
                .participationDate(participationDate)
                .score(request.getScore() == null ? 0 : request.getScore())
                .build();

        return toParticipationResponse(participationRepository.save(participation));
    }

    @Transactional(readOnly = true)
    public boolean hasUserJoined(Long eventId, Long participantId, ParticipantType participantType) {
        return participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantType(eventId, participantId, participantType);
    }

    @Transactional(readOnly = true)
    public StreakResponse calculateStreak(Long eventId, Long participantId, ParticipantType participantType) {
        List<LocalDate> dates = participationRepository.findDistinctParticipationDates(eventId, participantId, participantType);
        if (dates.isEmpty()) {
            return StreakResponse.builder()
                    .medicalEventId(eventId)
                    .participantId(participantId)
                    .streakDays(0)
                    .build();
        }

        int streak = 1;
        for (int i = 0; i < dates.size() - 1; i++) {
            LocalDate current = dates.get(i);
            LocalDate next = dates.get(i + 1);
            if (current.minusDays(1).equals(next)) {
                streak++;
            } else {
                break;
            }
        }

        return StreakResponse.builder()
                .medicalEventId(eventId)
                .participantId(participantId)
                .streakDays(streak)
                .build();
    }

    @Transactional(readOnly = true)
    public ScoreResponse calculateTotalScore(Long eventId, Long participantId, ParticipantType participantType) {
        Integer totalScore = participationRepository.sumScoreByEventAndParticipant(eventId, participantId, participantType);
        return ScoreResponse.builder()
                .medicalEventId(eventId)
                .participantId(participantId)
                .totalScore(totalScore == null ? 0 : totalScore)
                .build();
    }

    @Transactional(readOnly = true)
    public List<ParticipantRankingResponse> getParticipantRanking(Long eventId) {
        getEventOrThrow(eventId);
        List<ParticipantRankingProjection> projections = participationRepository.rankingByMedicalEvent(eventId);
        List<ParticipantRankingResponse> responses = new ArrayList<>();

        int rank = 1;
        for (ParticipantRankingProjection projection : projections) {
            responses.add(ParticipantRankingResponse.builder()
                    .rank(rank++)
                    .participantId(projection.getParticipantId())
                    .participantType(projection.getParticipantType())
                    .totalScore(projection.getTotalScore())
                    .participations(projection.getParticipations())
                    .build());
        }

        return responses;
    }

    public int completeExpiredMedicalEvents() {
        return medicalEventRepository.completeExpiredEvents(LocalDateTime.now());
    }

    @Scheduled(cron = "${app.medical-event.complete-cron:0 5 * * * *}")
    public void completeExpiredMedicalEventsScheduler() {
        completeExpiredMedicalEvents();
    }

    private MedicalEvent getEventOrThrow(Long eventId) {
        return medicalEventRepository.findById(eventId)
                .orElseThrow(() -> new ResourceNotFoundException("MedicalEvent not found: " + eventId));
    }

    private void validateDateRange(LocalDateTime startDate, LocalDateTime endDate) {
        if (startDate == null || endDate == null || !endDate.isAfter(startDate)) {
            throw new BusinessException("endDate must be after startDate.");
        }
    }

    private MedicalEventResponse toResponse(MedicalEvent event) {
        long participationCount = event.getParticipations() == null ? 0L : event.getParticipations().size();

        return MedicalEventResponse.builder()
                .id(event.getId())
                .title(event.getTitle())
                .description(event.getDescription())
                .type(event.getType())
                .difficulty(event.getDifficulty())
                .status(event.getStatus())
                .patientId(event.getPatientId())
                .familyId(event.getFamilyId())
                .startDate(event.getStartDate())
                .endDate(event.getEndDate())
                .autoGenerated(event.getAutoGenerated())
                .participationCount(participationCount)
                .createdAt(event.getCreatedAt())
                .updatedAt(event.getUpdatedAt())
                .build();
    }

    private MedicalEventParticipationResponse toParticipationResponse(MedicalEventParticipation participation) {
        return MedicalEventParticipationResponse.builder()
                .id(participation.getId())
                .medicalEventId(participation.getMedicalEvent().getId())
                .participantId(participation.getParticipantId())
                .participantType(participation.getParticipantType())
                .participationDate(participation.getParticipationDate())
                .score(participation.getScore())
                .createdAt(participation.getCreatedAt())
                .build();
    }
}
