spring.application.name=medical_report_service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/medical_report_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.docker.compose.enabled=false
users.service.url=http://localhost:8082

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ----- Mail (example SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=idriss.ghofrane123@gmail.com
spring.mail.password=sbzvujpzbzaqayjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ----- GCS
gcs.project-id=medical-report-project
gcs.bucket=medical-reports-bucket
gcs.credentials.path=classpath:gcp/service-account.json


cloudinary.cloud_name=dpgdgonfl
cloudinary.api_key=177417844695726
cloudinary.api_secret=w8wJ0oLex6rAjbCqrC8O9w3cROc