package tn.esprit.recommendation_service.dto.medicalevent;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import tn.esprit.recommendation_service.enums.DifficultyLevel;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MedicalEventResponse {

    private Long id;
    private String title;
    private String description;
    private MedicalEventType type;
    private DifficultyLevel difficulty;
    private MedicalEventStatus status;
    private Long patientId;
    private Long familyId;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    private Boolean autoGenerated;
    private Long participationCount;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
