global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mindcare-traitement-consultation'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['traitement-service:8081']

  - job_name: 'mindcare-ordonnance-medicaments'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ordonnance-service:8083']
