apiVersion: apps/v1
kind: Deployment
metadata:
  name: localization-service
  namespace: mindcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localization-service
  template:
    metadata:
      labels:
        app: localization-service
    spec:
      containers:
        - name: localization-service
          image: mindcare/localization-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: LOCALIZATION_DB_URL
              value: "jdbc:mysql://mysql:3306/localization_db?createDatabaseIfNotExist=true"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: localization-service
  namespace: mindcare
spec:
  selector:
    app: localization-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
