apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-report-service
  namespace: mindcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-report-service
  template:
    metadata:
      labels:
        app: medical-report-service
    spec:
      containers:
        - name: medical-report-service
          image: mindcare/medical-report-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/medical_report_db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: medical-report-service
  namespace: mindcare
spec:
  selector:
    app: medical-report-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
