apiVersion: apps/v1
kind: Deployment
metadata:
  name: traitement-et-consultation
  namespace: mindcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traitement-et-consultation
  template:
    metadata:
      labels:
        app: traitement-et-consultation
    spec:
      containers:
        - name: traitement-et-consultation
          image: mindcare/traitement-et-consultation:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/alzheimer_db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: traitement-et-consultation
  namespace: mindcare
spec:
  selector:
    app: traitement-et-consultation
  ports:
    - port: 8089
      targetPort: 8089
  type: ClusterIP
