package tn.esprit.medical_report_service.Services;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;
import tn.esprit.medical_report_service.Enteties.MedicalReport;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfService {

    public byte[] generateMedicalReportPdf(MedicalReport report) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        DeviceRgb tealColor = new DeviceRgb(9, 154, 167);
        DeviceRgb lightGray = new DeviceRgb(245, 247, 250);

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document doc = new Document(pdf);

            // ─── Header ───
            doc.add(new Paragraph("MEDICAL REPORT")
                    .setBold()
                    .setFontSize(22)
                    .setFontColor(tealColor)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(4));

            doc.add(new Paragraph("MindCare — Medical Report Service")
                    .setFontSize(10)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            // ─── Data Table ───
            Table table = new Table(UnitValue.createPercentArray(new float[] { 1, 2 }))
                    .useAllAvailableWidth()
                    .setMarginBottom(20);

            addTableRow(table, "Report ID", "#" + report.getReportid(), tealColor);
            addTableRow(table, "Title", report.getTitle(), tealColor);
            addTableRow(table, "Status", (report.getStatus() != null ? report.getStatus().name() : "N/A"), tealColor);
            addTableRow(table, "Patient", report.getPatientName(), tealColor);
            addTableRow(table, "Doctor", report.getDoctorName(), tealColor);
            addTableRow(table, "Created At",
                    report.getCreatedAt() != null ? report.getCreatedAt().format(formatter) : "N/A", tealColor);

            if (report.getApprovedAt() != null) {
                addTableRow(table, "Approved At", report.getApprovedAt().format(formatter), tealColor);
            }

            doc.add(table);

            // ─── Description ───
            doc.add(new Paragraph("Description")
                    .setBold()
                    .setFontSize(14)
                    .setFontColor(tealColor)
                    .setMarginBottom(6));

            String desc = (report.getDescription() != null && !report.getDescription().isBlank())
                    ? report.getDescription()
                    : "No description provided.";

            doc.add(new Paragraph(desc)
                    .setFontSize(11)
                    .setBackgroundColor(lightGray)
                    .setPadding(12));

            // ─── Footer ───
            doc.add(new Paragraph("Generated by MindCare System")
                    .setFontSize(8)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(30));

            doc.close();

        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF: " + e.getMessage(), e);
        }

        return out.toByteArray();
    }

    private void addTableRow(Table table, String label, String value, DeviceRgb headerColor) {
        table.addCell(new Cell()
                .add(new Paragraph(label == null ? "" : label).setBold().setFontSize(10)
                        .setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(headerColor)
                .setPadding(8));
        table.addCell(new Cell()
                .add(new Paragraph(value == null ? "—" : value).setFontSize(10))
                .setPadding(8));
    }
}
