pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'Amena-Farah-Finale',
                    url: 'https://github.com/ghofraneidriss/Esprit-PI-4SAE6-2026-mind-care.git'
            }
        }

        stage('Build & Install Parent') {
            steps {
                dir('server') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test & Jacoco Report') {
            steps {
                dir('server/forums_service') {
                    sh 'mvn org.jacoco:jacoco-maven-plugin:0.8.11:prepare-agent test org.jacoco:jacoco-maven-plugin:0.8.11:report -Dtest=!ForumsServiceApplicationTests'
                }
                dir('server/incident_service') {
                    sh 'mvn org.jacoco:jacoco-maven-plugin:0.8.11:prepare-agent test org.jacoco:jacoco-maven-plugin:0.8.11:report -Dtest=!IncidentServiceApplicationTests'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                          testResults: 'server/**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('server/forums_service') {
                        sh """
                            mvn sonar:sonar \
                              -Dsonar.projectKey=forums-service \
                              -Dsonar.projectName="Forums Service" \
                              -Dsonar.coverage.jacoco.xmlReportPaths=\${WORKSPACE}/server/forums_service/target/site/jacoco/jacoco.xml
                        """
                    }
                    dir('server/incident_service') {
                        sh """
                            mvn sonar:sonar \
                              -Dsonar.projectKey=incident-service \
                              -Dsonar.projectName="Incident Service" \
                              -Dsonar.coverage.jacoco.xmlReportPaths=\${WORKSPACE}/server/incident_service/target/site/jacoco/jacoco.xml
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 15, unit: 'MINUTES') {
                    // abortPipeline: false permet de continuer même si le gate met trop de temps
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t mindcare-alzheimer-forums:1.0 server/forums_service/'
                sh 'docker build -t mindcare-alzheimer-incident:1.0 server/incident_service/'
                sh 'docker tag mindcare-alzheimer-forums:1.0 mindcare-alzheimer-forums:latest'
                sh 'docker tag mindcare-alzheimer-incident:1.0 mindcare-alzheimer-incident:latest'
            }
        }

        stage('Deploy to Artifactory') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'artifactory-creds',
                    usernameVariable: 'ARTIF_USER',
                    passwordVariable: 'ARTIF_PASS'
                )]) {
                    dir('server') {
                       sh """
                            echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"><servers><server><id>artifactory-server</id><username>\${ARTIF_USER}</username><password>\${ARTIF_PASS}</password></server></servers></settings>' > settings_jenkins.xml
                            mvn deploy -DskipTests \
                            --settings ./settings_jenkins.xml \
                            -DaltDeploymentRepository="artifactory-server::http://172.19.224.221:8082/artifactory/libs-snapshot-local" \
                            -U

                           """
                    }
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'server/**/*.jar', fingerprint: true
            echo '✅ Pipeline réussi — Tests + JaCoCo + SonarQube + Docker + Artifactory OK !'
        }
        failure {
            echo '❌ Pipeline échoué — Vérifie les logs.'
        }
    }
}