apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: mysql
    user: root
    secureJsonData:
      password: ""
    jsonData:
      sslmode: disable
      allowInsecureUiUpdate: true
    editable: true
    isDefault: false
