package tn.esprit.recommendation_service.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import tn.esprit.recommendation_service.dto.sudoku.SudokuCreateRequest;
import tn.esprit.recommendation_service.dto.sudoku.SudokuResponse;
import tn.esprit.recommendation_service.dto.sudoku.SudokuSessionStartResponse;
import tn.esprit.recommendation_service.dto.sudoku.SudokuSessionSubmitRequest;
import tn.esprit.recommendation_service.dto.sudoku.SudokuSessionResponse;
import tn.esprit.recommendation_service.entity.MedicalEvent;
import tn.esprit.recommendation_service.entity.SudokuGame;
import tn.esprit.recommendation_service.entity.SudokuSession;
import tn.esprit.recommendation_service.enums.DifficultyLevel;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;
import tn.esprit.recommendation_service.exception.BusinessException;
import tn.esprit.recommendation_service.exception.ResourceNotFoundException;
import tn.esprit.recommendation_service.repository.MedicalEventRepository;
import tn.esprit.recommendation_service.repository.SudokuGameRepository;
import tn.esprit.recommendation_service.repository.SudokuSessionRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("SudokuService — Tests Unitaires")
class SudokuServiceTest {

    @Mock private SudokuGameRepository sudokuGameRepository;
    @Mock private SudokuSessionRepository sudokuSessionRepository;
    @Mock private MedicalEventRepository medicalEventRepository;
    @Mock private ObjectMapper objectMapper;

    @InjectMocks
    private SudokuService sudokuService;

    private MedicalEvent sampleEvent;
    private SudokuGame sampleGame;

    @BeforeEach
    void setUp() throws Exception {
        sampleEvent = MedicalEvent.builder()
                .id(10L).title("Sudoku thérapeutique")
                .type(MedicalEventType.SUDOKU).difficulty(DifficultyLevel.EASY)
                .status(MedicalEventStatus.ACTIVE).patientId(4L)
                .startDate(LocalDateTime.now()).endDate(LocalDateTime.now().plusDays(30))
                .autoGenerated(false).build();

        sampleGame = SudokuGame.builder()
                .id(1L).medicalEvent(sampleEvent).patientId(4L)
                .difficulty(DifficultyLevel.EASY).gridSize(4)
                .puzzle("[[1,2,0,4],[3,0,1,2],[2,1,4,3],[4,3,2,0]]")
                .solution("[[1,2,3,4],[3,4,1,2],[2,1,4,3],[4,3,2,1]]")
                .timeLimitSeconds(300).active(true).completedSessions(0).build();

        when(objectMapper.writeValueAsString(any())).thenReturn("[[1,2,3,4]]");
    }

    // ── Génération de grille ──────────────────────────────────────────────────

    @Nested
    @DisplayName("Génération de grille Sudoku")
    class GridGeneration {

        @Test
        @DisplayName("generateSolution(4) produit une grille 4x4 valide")
        void generateSolution_4x4_isValid() {
            int[][] grid = sudokuService.generateSolution(4);

            assertThat(grid).hasNumberOfRows(4);
            assertThat(grid[0]).hasSize(4);

            // Chaque ligne contient 1,2,3,4
            for (int[] row : grid) {
                assertThat(row).containsExactlyInAnyOrder(1, 2, 3, 4);
            }

            // Chaque colonne contient 1,2,3,4
            for (int col = 0; col < 4; col++) {
                int[] column = new int[4];
                for (int row = 0; row < 4; row++) column[row] = grid[row][col];
                assertThat(column).containsExactlyInAnyOrder(1, 2, 3, 4);
            }
        }

        @Test
        @DisplayName("generateSolution(4) — chaque sous-grille 2x2 contient 1,2,3,4")
        void generateSolution_4x4_subGridsValid() {
            int[][] grid = sudokuService.generateSolution(4);

            // Sous-grille haut-gauche
            assertThat(new int[]{grid[0][0], grid[0][1], grid[1][0], grid[1][1]})
                    .containsExactlyInAnyOrder(1, 2, 3, 4);
            // Sous-grille haut-droite
            assertThat(new int[]{grid[0][2], grid[0][3], grid[1][2], grid[1][3]})
                    .containsExactlyInAnyOrder(1, 2, 3, 4);
        }

        @Test
        @DisplayName("generatePuzzle EASY retire exactement 6 cellules")
        void generatePuzzle_easy_removes6Cells() {
            int[][] solution = sudokuService.generateSolution(4);
            int[][] puzzle = sudokuService.generatePuzzle(solution, DifficultyLevel.EASY);

            int zeroCount = 0;
            for (int[] row : puzzle) {
                for (int cell : row) {
                    if (cell == 0) zeroCount++;
                }
            }
            assertThat(zeroCount).isEqualTo(6);
        }

        @Test
        @DisplayName("isValid retourne false si doublon dans la ligne")
        void isValid_duplicateInRow_returnsFalse() {
            int[][] grid = new int[4][4];
            grid[0][0] = 1;
            assertThat(sudokuService.isValid(grid, 0, 1, 1, 4)).isFalse();
        }

        @Test
        @DisplayName("isValid retourne false si doublon dans la colonne")
        void isValid_duplicateInColumn_returnsFalse() {
            int[][] grid = new int[4][4];
            grid[0][0] = 2;
            assertThat(sudokuService.isValid(grid, 1, 0, 2, 4)).isFalse();
        }

        @Test
        @DisplayName("isValid retourne true si placement valide")
        void isValid_validPlacement_returnsTrue() {
            int[][] grid = new int[4][4];
            assertThat(sudokuService.isValid(grid, 0, 0, 1, 4)).isTrue();
        }
    }

    // ── createGame ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("createGame")
    class CreateGame {

        @Test
        @DisplayName("Crée un jeu Sudoku EASY avec succès")
        void createGame_easy_success() {
            SudokuCreateRequest request = SudokuCreateRequest.builder()
                    .patientId(4L).difficulty(DifficultyLevel.EASY)
                    .timeLimitSeconds(300).title("Sudoku test").build();

            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            when(sudokuGameRepository.save(any())).thenReturn(sampleGame);

            SudokuResponse response = sudokuService.createGame(request);

            assertThat(response).isNotNull();
            assertThat(response.getPatientId()).isEqualTo(4L);
            assertThat(response.getGridSize()).isEqualTo(4);
            assertThat(response.getDifficulty()).isEqualTo(DifficultyLevel.EASY);
            verify(medicalEventRepository).save(argThat(e ->
                    e.getType() == MedicalEventType.SUDOKU &&
                    e.getStatus() == MedicalEventStatus.ACTIVE));
        }

        @Test
        @DisplayName("Lève BusinessException si patientId est null")
        void createGame_nullPatientId_throws() {
            SudokuCreateRequest request = SudokuCreateRequest.builder()
                    .patientId(null).difficulty(DifficultyLevel.EASY).build();

            assertThatThrownBy(() -> sudokuService.createGame(request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("patientId");
        }

        @Test
        @DisplayName("Lève BusinessException si patientId <= 0")
        void createGame_zeroPatientId_throws() {
            SudokuCreateRequest request = SudokuCreateRequest.builder()
                    .patientId(0L).difficulty(DifficultyLevel.EASY).build();

            assertThatThrownBy(() -> sudokuService.createGame(request))
                    .isInstanceOf(BusinessException.class);
        }

        @Test
        @DisplayName("gridSize = 4 pour EASY")
        void createGame_easy_gridSizeIs4() {
            SudokuCreateRequest request = SudokuCreateRequest.builder()
                    .patientId(4L).difficulty(DifficultyLevel.EASY).build();
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            when(sudokuGameRepository.save(any())).thenReturn(sampleGame);

            sudokuService.createGame(request);

            verify(sudokuGameRepository).save(argThat(g -> g.getGridSize() == 4));
        }

        @Test
        @DisplayName("timeLimitSeconds par défaut = 300 si non fourni")
        void createGame_defaultTimeLimit() {
            SudokuCreateRequest request = SudokuCreateRequest.builder()
                    .patientId(4L).difficulty(DifficultyLevel.EASY)
                    .timeLimitSeconds(null).build();
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            when(sudokuGameRepository.save(any())).thenReturn(sampleGame);

            sudokuService.createGame(request);

            verify(sudokuGameRepository).save(argThat(g -> g.getTimeLimitSeconds() == 300));
        }
    }

    // ── getByEvent ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("getByEvent")
    class GetByEvent {

        @Test
        @DisplayName("Retourne le jeu si l'eventId existe")
        void getByEvent_found() {
            when(sudokuGameRepository.findByMedicalEvent_Id(10L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findBySudokuGame_IdAndCompletedTrueOrderByScoreDescDurationSecondsAsc(1L))
                    .thenReturn(List.of());

            SudokuResponse response = sudokuService.getByEvent(10L);

            assertThat(response.getMedicalEventId()).isEqualTo(10L);
        }

        @Test
        @DisplayName("Lève ResourceNotFoundException si eventId inconnu")
        void getByEvent_notFound() {
            when(sudokuGameRepository.findByMedicalEvent_Id(99L)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> sudokuService.getByEvent(99L))
                    .isInstanceOf(ResourceNotFoundException.class)
                    .hasMessageContaining("99");
        }
    }

    // ── startSession ──────────────────────────────────────────────────────────

    @Nested
    @DisplayName("startSession")
    class StartSession {

        @Test
        @DisplayName("Démarre une session avec succès")
        void startSession_success() {
            SudokuSession session = SudokuSession.builder()
                    .id(1L).sudokuGame(sampleGame).patientId(4L)
                    .startedAt(LocalDateTime.now()).completed(false).abandoned(false)
                    .errorsCount(0).hintsUsed(0).completionPercent(0).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.save(any())).thenReturn(session);

            SudokuSessionStartResponse response = sudokuService.startSession(1L, 4L);

            assertThat(response.getSessionId()).isEqualTo(1L);
            assertThat(response.getPatientId()).isEqualTo(4L);
            verify(sudokuSessionRepository).save(argThat(s ->
                    s.getPatientId().equals(4L) &&
                    !s.getCompleted() && !s.getAbandoned()));
        }

        @Test
        @DisplayName("Lève ResourceNotFoundException si gameId inconnu")
        void startSession_gameNotFound() {
            when(sudokuGameRepository.findById(99L)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> sudokuService.startSession(99L, 4L))
                    .isInstanceOf(ResourceNotFoundException.class);
        }
    }

    // ── submitSession ─────────────────────────────────────────────────────────

    @Nested
    @DisplayName("submitSession")
    class SubmitSession {

        private SudokuSession openSession;

        @BeforeEach
        void setUpSession() {
            openSession = SudokuSession.builder()
                    .id(5L).sudokuGame(sampleGame).patientId(4L)
                    .startedAt(LocalDateTime.now().minusMinutes(3))
                    .completed(false).abandoned(false)
                    .errorsCount(0).hintsUsed(0).completionPercent(0).build();
        }

        @Test
        @DisplayName("Soumet une session complétée et calcule le score")
        void submitSession_completed_calculatesScore() {
            SudokuSessionSubmitRequest request = SudokuSessionSubmitRequest.builder()
                    .patientId(4L).durationSeconds(180).errorsCount(0)
                    .hintsUsed(0).completionPercent(100).completed(true).abandoned(false).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));
            when(sudokuSessionRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
            when(sudokuGameRepository.save(any())).thenReturn(sampleGame);

            SudokuSessionResponse response = sudokuService.submitSession(1L, 5L, request);

            assertThat(response.getCompleted()).isTrue();
            assertThat(response.getScore()).isGreaterThan(0);
        }

        @Test
        @DisplayName("Score = 0 si session abandonnée")
        void submitSession_abandoned_scoreIsZero() {
            SudokuSessionSubmitRequest request = SudokuSessionSubmitRequest.builder()
                    .patientId(4L).durationSeconds(60).errorsCount(2)
                    .hintsUsed(1).completionPercent(50).completed(false).abandoned(true).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));
            when(sudokuSessionRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

            SudokuSessionResponse response = sudokuService.submitSession(1L, 5L, request);

            assertThat(response.getScore()).isEqualTo(0);
            assertThat(response.getAbandoned()).isTrue();
        }

        @Test
        @DisplayName("Lève BusinessException si session déjà soumise")
        void submitSession_alreadySubmitted_throws() {
            openSession.setFinishedAt(LocalDateTime.now());
            SudokuSessionSubmitRequest request = SudokuSessionSubmitRequest.builder()
                    .patientId(4L).completed(true).abandoned(false).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));

            assertThatThrownBy(() -> sudokuService.submitSession(1L, 5L, request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("already been submitted");
        }

        @Test
        @DisplayName("Lève BusinessException si patientId ne correspond pas")
        void submitSession_wrongPatient_throws() {
            SudokuSessionSubmitRequest request = SudokuSessionSubmitRequest.builder()
                    .patientId(99L).completed(true).abandoned(false).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));

            assertThatThrownBy(() -> sudokuService.submitSession(1L, 5L, request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("patient");
        }

        @Test
        @DisplayName("Met à jour bestScore si score supérieur")
        void submitSession_updatesBestScore() {
            sampleGame.setBestScore(100);
            SudokuSessionSubmitRequest request = SudokuSessionSubmitRequest.builder()
                    .patientId(4L).durationSeconds(100).errorsCount(0)
                    .hintsUsed(0).completionPercent(100).completed(true).abandoned(false).build();

            when(sudokuGameRepository.findById(1L)).thenReturn(Optional.of(sampleGame));
            when(sudokuSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));
            when(sudokuSessionRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
            when(sudokuGameRepository.save(any())).thenReturn(sampleGame);

            sudokuService.submitSession(1L, 5L, request);

            verify(sudokuGameRepository).save(argThat(g -> g.getBestScore() >= 100));
        }
    }
}
