package tn.esprit.recommendation_service.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import tn.esprit.recommendation_service.dto.medicalevent.JoinMedicalEventRequest;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventCreateRequest;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventParticipationResponse;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventResponse;
import tn.esprit.recommendation_service.dto.medicalevent.MedicalEventUpdateRequest;
import tn.esprit.recommendation_service.dto.medicalevent.ParticipantRankingResponse;
import tn.esprit.recommendation_service.dto.medicalevent.ScoreResponse;
import tn.esprit.recommendation_service.dto.medicalevent.StreakResponse;
import tn.esprit.recommendation_service.entity.MedicalEvent;
import tn.esprit.recommendation_service.entity.MedicalEventParticipation;
import tn.esprit.recommendation_service.enums.DifficultyLevel;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;
import tn.esprit.recommendation_service.enums.ParticipantType;
import tn.esprit.recommendation_service.exception.BusinessException;
import tn.esprit.recommendation_service.exception.ResourceNotFoundException;
import tn.esprit.recommendation_service.repository.MedicalEventParticipationRepository;
import tn.esprit.recommendation_service.repository.MedicalEventRepository;
import tn.esprit.recommendation_service.repository.projection.ParticipantRankingProjection;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class MedicalEventServiceTest {

    @Mock
    private MedicalEventRepository medicalEventRepository;

    @Mock
    private MedicalEventParticipationRepository participationRepository;

    @InjectMocks
    private MedicalEventService service;

    private MedicalEvent event;
    private LocalDateTime startDate;
    private LocalDateTime endDate;

    @BeforeEach
    void setUp() {
        startDate = LocalDateTime.now().plusDays(1);
        endDate = startDate.plusDays(2);
        event = MedicalEvent.builder()
                .id(1L)
                .title("Atelier memo")
                .description("desc")
                .type(MedicalEventType.SUDOKU)
                .difficulty(DifficultyLevel.EASY)
                .status(MedicalEventStatus.ACTIVE)
                .patientId(10L)
                .familyId(20L)
                .startDate(startDate)
                .endDate(endDate)
                .autoGenerated(false)
                .participations(List.of())
                .build();
    }

    @Test
    void createMedicalEvent_shouldSaveAndMapResponse() {
        MedicalEventCreateRequest request = MedicalEventCreateRequest.builder()
                .title("Atelier memo")
                .description("desc")
                .type(MedicalEventType.SUDOKU)
                .difficulty(DifficultyLevel.EASY)
                .patientId(10L)
                .familyId(20L)
                .startDate(startDate)
                .endDate(endDate)
                .build();
        when(medicalEventRepository.save(any(MedicalEvent.class))).thenReturn(event);

        MedicalEventResponse response = service.createMedicalEvent(request);

        assertThat(response.getTitle()).isEqualTo("Atelier memo");
        assertThat(response.getStatus()).isEqualTo(MedicalEventStatus.ACTIVE);
    }

    @Test
    void createMedicalEvent_shouldRejectInvalidDates() {
        MedicalEventCreateRequest request = MedicalEventCreateRequest.builder()
                .title("Invalid")
                .type(MedicalEventType.SUDOKU)
                .patientId(10L)
                .startDate(startDate)
                .endDate(startDate.minusHours(1))
                .build();

        assertThatThrownBy(() -> service.createMedicalEvent(request))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("endDate");
    }

    @Test
    void queryMethods_shouldDelegateToRepositoryAndMapResults() {
        when(medicalEventRepository.findAll()).thenReturn(List.of(event));
        when(medicalEventRepository.findByTitleContainingIgnoreCaseOrDescriptionContainingIgnoreCase("memo", "memo"))
                .thenReturn(List.of(event));
        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));
        when(medicalEventRepository.findByPatientIdAndStatusOrderByCreatedAtDesc(10L, MedicalEventStatus.ACTIVE))
                .thenReturn(List.of(event));
        when(medicalEventRepository.findByTypeOrderByCreatedAtDesc(MedicalEventType.SUDOKU))
                .thenReturn(List.of(event));
        when(medicalEventRepository.findByPatientIdAndStatusOrderByEndDateDesc(10L, MedicalEventStatus.COMPLETED))
                .thenReturn(List.of(event));

        assertThat(service.getAllMedicalEvents()).hasSize(1);
        assertThat(service.searchMedicalEvents("memo")).hasSize(1);
        assertThat(service.getMedicalEventById(1L).getId()).isEqualTo(1L);
        assertThat(service.getActiveMedicalEventsByPatient(10L)).hasSize(1);
        assertThat(service.getMedicalEventsByType(MedicalEventType.SUDOKU)).hasSize(1);
        assertThat(service.getCompletedMedicalEvents(10L)).hasSize(1);
    }

    @Test
    void getMedicalEventById_shouldThrowWhenMissing() {
        when(medicalEventRepository.findById(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.getMedicalEventById(999L))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    void updateMedicalEvent_shouldUpdateFieldsAndSave() {
        MedicalEventUpdateRequest request = MedicalEventUpdateRequest.builder()
                .title("Updated")
                .description("new")
                .type(MedicalEventType.PUZZLE)
                .difficulty(DifficultyLevel.HARD)
                .status(MedicalEventStatus.COMPLETED)
                .patientId(30L)
                .familyId(40L)
                .startDate(startDate.plusDays(1))
                .endDate(endDate.plusDays(1))
                .build();
        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));
        when(medicalEventRepository.save(event)).thenReturn(event);

        MedicalEventResponse response = service.updateMedicalEvent(1L, request);

        assertThat(event.getTitle()).isEqualTo("Updated");
        assertThat(event.getType()).isEqualTo(MedicalEventType.PUZZLE);
        assertThat(event.getStatus()).isEqualTo(MedicalEventStatus.COMPLETED);
        assertThat(response.getTitle()).isEqualTo("Updated");
    }

    @Test
    void deleteMedicalEvent_shouldDeleteOnlyBeforeStart() {
        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));

        service.deleteMedicalEvent(1L);
        verify(medicalEventRepository).delete(event);

        event.setStartDate(LocalDateTime.now().minusMinutes(1));
        assertThatThrownBy(() -> service.deleteMedicalEvent(1L))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("deleted only before");
    }

    @Test
    void joinMedicalEvent_shouldSaveParticipation() {
        JoinMedicalEventRequest request = JoinMedicalEventRequest.builder()
                .participantId(50L)
                .participantType(ParticipantType.PATIENT)
                .participationDate(startDate.toLocalDate())
                .score(80)
                .build();
        MedicalEventParticipation participation = MedicalEventParticipation.builder()
                .id(3L)
                .medicalEvent(event)
                .participantId(50L)
                .participantType(ParticipantType.PATIENT)
                .participationDate(startDate.toLocalDate())
                .score(80)
                .build();

        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));
        when(participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantTypeAndParticipationDate(
                1L, 50L, ParticipantType.PATIENT, startDate.toLocalDate())).thenReturn(false);
        when(participationRepository.save(any(MedicalEventParticipation.class))).thenReturn(participation);

        MedicalEventParticipationResponse response = service.joinMedicalEvent(1L, request);

        assertThat(response.getMedicalEventId()).isEqualTo(1L);
        assertThat(response.getScore()).isEqualTo(80);
    }

    @Test
    void joinMedicalEvent_shouldRejectInvalidParticipationCases() {
        JoinMedicalEventRequest request = JoinMedicalEventRequest.builder()
                .participantId(50L)
                .participantType(ParticipantType.PATIENT)
                .participationDate(startDate.minusDays(2).toLocalDate())
                .build();
        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));

        assertThatThrownBy(() -> service.joinMedicalEvent(1L, request))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("between startDate and endDate");

        request.setParticipationDate(startDate.toLocalDate());
        when(participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantTypeAndParticipationDate(
                1L, 50L, ParticipantType.PATIENT, startDate.toLocalDate())).thenReturn(true);

        assertThatThrownBy(() -> service.joinMedicalEvent(1L, request))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("already joined");
    }

    @Test
    void participationMetrics_shouldBeCalculated() {
        when(participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantType(1L, 50L, ParticipantType.PATIENT))
                .thenReturn(true);
        when(participationRepository.findDistinctParticipationDates(1L, 50L, ParticipantType.PATIENT))
                .thenReturn(List.of(LocalDate.now(), LocalDate.now().minusDays(1), LocalDate.now().minusDays(2)));
        when(participationRepository.sumScoreByEventAndParticipant(1L, 50L, ParticipantType.PATIENT))
                .thenReturn(null);

        assertThat(service.hasUserJoined(1L, 50L, ParticipantType.PATIENT)).isTrue();
        StreakResponse streak = service.calculateStreak(1L, 50L, ParticipantType.PATIENT);
        ScoreResponse score = service.calculateTotalScore(1L, 50L, ParticipantType.PATIENT);

        assertThat(streak.getStreakDays()).isEqualTo(3);
        assertThat(score.getTotalScore()).isZero();
    }

    @Test
    void calculateStreak_shouldReturnZeroWhenNoDates() {
        when(participationRepository.findDistinctParticipationDates(anyLong(), anyLong(), any())).thenReturn(List.of());

        StreakResponse response = service.calculateStreak(1L, 2L, ParticipantType.FAMILY);

        assertThat(response.getStreakDays()).isZero();
    }

    @Test
    void getParticipantRanking_shouldAssignRanks() {
        ParticipantRankingProjection projection1 = new ParticipantRankingProjection() {
            @Override public Long getParticipantId() { return 10L; }
            @Override public ParticipantType getParticipantType() { return ParticipantType.PATIENT; }
            @Override public Long getTotalScore() { return 120L; }
            @Override public Long getParticipations() { return 3L; }
        };
        ParticipantRankingProjection projection2 = new ParticipantRankingProjection() {
            @Override public Long getParticipantId() { return 20L; }
            @Override public ParticipantType getParticipantType() { return ParticipantType.FAMILY; }
            @Override public Long getTotalScore() { return 90L; }
            @Override public Long getParticipations() { return 2L; }
        };
        when(medicalEventRepository.findById(1L)).thenReturn(Optional.of(event));
        when(participationRepository.rankingByMedicalEvent(1L)).thenReturn(List.of(projection1, projection2));

        List<ParticipantRankingResponse> ranking = service.getParticipantRanking(1L);

        assertThat(ranking).hasSize(2);
        assertThat(ranking.get(0).getRank()).isEqualTo(1);
        assertThat(ranking.get(1).getRank()).isEqualTo(2);
    }

    @Test
    void completeExpiredMedicalEvents_shouldDelegateToRepository() {
        when(medicalEventRepository.completeExpiredEvents(any(LocalDateTime.class))).thenReturn(6);

        assertThat(service.completeExpiredMedicalEvents()).isEqualTo(6);
        service.completeExpiredMedicalEventsScheduler();
        verify(medicalEventRepository, org.mockito.Mockito.times(2)).completeExpiredEvents(any(LocalDateTime.class));
    }
}
