package tn.esprit.recommendation_service.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.client.RestTemplate;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleCreateRequest;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleResponse;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionStartResponse;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionSubmitRequest;
import tn.esprit.recommendation_service.dto.puzzle.PuzzleSessionResponse;
import tn.esprit.recommendation_service.dto.puzzle.SouvenirSourceSummary;
import tn.esprit.recommendation_service.entity.MedicalEvent;
import tn.esprit.recommendation_service.entity.PuzzleSession;
import tn.esprit.recommendation_service.entity.SouvenirPuzzle;
import tn.esprit.recommendation_service.enums.DifficultyLevel;
import tn.esprit.recommendation_service.enums.MedicalEventStatus;
import tn.esprit.recommendation_service.enums.MedicalEventType;
import tn.esprit.recommendation_service.enums.PuzzleStatus;
import tn.esprit.recommendation_service.exception.BusinessException;
import tn.esprit.recommendation_service.exception.ResourceNotFoundException;
import tn.esprit.recommendation_service.repository.MedicalEventParticipationRepository;
import tn.esprit.recommendation_service.repository.MedicalEventRepository;
import tn.esprit.recommendation_service.repository.PuzzleSessionRepository;
import tn.esprit.recommendation_service.repository.SouvenirPuzzleRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("SouvenirPuzzleService — Tests Unitaires")
class SouvenirPuzzleServiceTest {

    @Mock private SouvenirPuzzleRepository souvenirPuzzleRepository;
    @Mock private PuzzleSessionRepository puzzleSessionRepository;
    @Mock private MedicalEventRepository medicalEventRepository;
    @Mock private MedicalEventParticipationRepository participationRepository;
    @Mock private PatientStatsService patientStatsService;
    @Mock private RestTemplate restTemplate;

    @InjectMocks
    private SouvenirPuzzleService service;

    private MedicalEvent sampleEvent;
    private SouvenirPuzzle samplePuzzle;
    private SouvenirSourceSummary sampleSouvenir;

    @BeforeEach
    void setUp() {
        sampleEvent = MedicalEvent.builder()
                .id(10L).title("Puzzle Mariage").type(MedicalEventType.PUZZLE)
                .difficulty(DifficultyLevel.MEDIUM).status(MedicalEventStatus.ACTIVE)
                .patientId(4L).startDate(LocalDateTime.now())
                .endDate(LocalDateTime.now().plusDays(7)).autoGenerated(false).build();

        samplePuzzle = SouvenirPuzzle.builder()
                .id(1L).medicalEvent(sampleEvent).souvenirEntryId(42L)
                .patientId(4L).title("Puzzle Mariage 1985")
                .description("Photo du mariage").difficulty(DifficultyLevel.MEDIUM)
                .gridSize(4).timeLimitSeconds(300).maxHints(3)
                .status(PuzzleStatus.ACTIVE).build();

        sampleSouvenir = SouvenirSourceSummary.builder()
                .id(42L).patientId(4L).mediaType("IMAGE")
                .mediaUrl("http://localhost:8086/files/mariage.jpg")
                .mediaTitle("Mariage 1985").texte("Photo du mariage").build();
    }

    // ── gridSize ──────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Calcul gridSize selon difficulté")
    class GridSize {

        @Test
        @DisplayName("EASY → gridSize = 3")
        void easy_gridSize3() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.EASY);
            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            SouvenirPuzzle easyPuzzle = SouvenirPuzzle.builder().id(1L).medicalEvent(sampleEvent)
                    .souvenirEntryId(42L).patientId(4L).title("T").difficulty(DifficultyLevel.EASY)
                    .gridSize(3).timeLimitSeconds(300).maxHints(3).status(PuzzleStatus.ACTIVE).build();
            when(souvenirPuzzleRepository.save(any())).thenReturn(easyPuzzle);
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());

            PuzzleResponse response = service.createPuzzle(request);

            assertThat(response.getGridSize()).isEqualTo(3);
        }

        @Test
        @DisplayName("MEDIUM → gridSize = 4")
        void medium_gridSize4() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.MEDIUM);
            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            when(souvenirPuzzleRepository.save(any())).thenReturn(samplePuzzle);
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());

            PuzzleResponse response = service.createPuzzle(request);

            assertThat(response.getGridSize()).isEqualTo(4);
        }

        @Test
        @DisplayName("HARD → gridSize = 5")
        void hard_gridSize5() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.HARD);
            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            SouvenirPuzzle hardPuzzle = SouvenirPuzzle.builder().id(1L).medicalEvent(sampleEvent)
                    .souvenirEntryId(42L).patientId(4L).title("T").difficulty(DifficultyLevel.HARD)
                    .gridSize(5).timeLimitSeconds(300).maxHints(3).status(PuzzleStatus.ACTIVE).build();
            when(souvenirPuzzleRepository.save(any())).thenReturn(hardPuzzle);
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());

            PuzzleResponse response = service.createPuzzle(request);

            assertThat(response.getGridSize()).isEqualTo(5);
        }
    }

    // ── createPuzzle ──────────────────────────────────────────────────────────

    @Nested
    @DisplayName("createPuzzle")
    class CreatePuzzle {

        @Test
        @DisplayName("Crée un puzzle avec succès")
        void createPuzzle_success() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.MEDIUM);
            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(medicalEventRepository.save(any())).thenReturn(sampleEvent);
            when(souvenirPuzzleRepository.save(any())).thenReturn(samplePuzzle);
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());

            PuzzleResponse response = service.createPuzzle(request);

            assertThat(response).isNotNull();
            assertThat(response.getPatientId()).isEqualTo(4L);
            verify(medicalEventRepository).save(argThat(e -> e.getType() == MedicalEventType.PUZZLE));
        }

        @Test
        @DisplayName("Lève BusinessException si puzzle déjà existant pour ce souvenir/patient")
        void createPuzzle_alreadyExists_throws() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.MEDIUM);
            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(true);

            assertThatThrownBy(() -> service.createPuzzle(request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("already exists");
        }

        @Test
        @DisplayName("Lève BusinessException si souvenir n'est pas IMAGE")
        void createPuzzle_notImageSouvenir_throws() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.MEDIUM);
            SouvenirSourceSummary audioSouvenir = SouvenirSourceSummary.builder()
                    .id(42L).patientId(4L).mediaType("AUDIO")
                    .mediaUrl("http://audio.url").build();

            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(audioSouvenir);

            assertThatThrownBy(() -> service.createPuzzle(request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("IMAGE");
        }

        @Test
        @DisplayName("Lève BusinessException si souvenir n'appartient pas au patient")
        void createPuzzle_souvenirWrongPatient_throws() {
            PuzzleCreateRequest request = buildRequest(DifficultyLevel.MEDIUM);
            SouvenirSourceSummary wrongPatientSouvenir = SouvenirSourceSummary.builder()
                    .id(42L).patientId(99L).mediaType("IMAGE")
                    .mediaUrl("http://img.url").build();

            when(souvenirPuzzleRepository.existsBySouvenirEntryIdAndPatientId(42L, 4L)).thenReturn(false);
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(wrongPatientSouvenir);

            assertThatThrownBy(() -> service.createPuzzle(request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("same patient");
        }
    }

    // ── startSession ──────────────────────────────────────────────────────────

    @Nested
    @DisplayName("startSession")
    class StartSession {

        @Test
        @DisplayName("Démarre une session avec succès")
        void startSession_success() {
            PuzzleSession session = PuzzleSession.builder()
                    .id(1L).puzzle(samplePuzzle).patientId(4L)
                    .startedAt(LocalDateTime.now()).completed(false).abandoned(false)
                    .movesCount(0).errorsCount(0).hintsUsed(0).completionPercent(0).build();

            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(puzzleSessionRepository.save(any())).thenReturn(session);

            PuzzleSessionStartResponse response = service.startSession(1L, 4L);

            assertThat(response.getSessionId()).isEqualTo(1L);
            assertThat(response.getPatientId()).isEqualTo(4L);
        }

        @Test
        @DisplayName("Lève BusinessException si patient ne correspond pas au puzzle")
        void startSession_wrongPatient_throws() {
            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);

            assertThatThrownBy(() -> service.startSession(1L, 99L))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("patient");
        }

        @Test
        @DisplayName("Lève BusinessException si puzzle INACTIVE")
        void startSession_inactivePuzzle_throws() {
            samplePuzzle.setStatus(PuzzleStatus.INACTIVE);
            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);

            assertThatThrownBy(() -> service.startSession(1L, 4L))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("inactive");
        }
    }

    // ── submitSession ─────────────────────────────────────────────────────────

    @Nested
    @DisplayName("submitSession — calcul du score")
    class SubmitSession {

        private PuzzleSession openSession;

        @BeforeEach
        void setUpSession() {
            openSession = PuzzleSession.builder()
                    .id(5L).puzzle(samplePuzzle).patientId(4L)
                    .startedAt(LocalDateTime.now().minusMinutes(4))
                    .completed(false).abandoned(false)
                    .movesCount(0).errorsCount(0).hintsUsed(0).completionPercent(0).build();
        }

        @Test
        @DisplayName("Score > 0 pour session complétée sans erreur ni indice")
        void submitSession_perfectScore_positive() {
            PuzzleSessionSubmitRequest request = PuzzleSessionSubmitRequest.builder()
                    .patientId(4L).durationSeconds(200).movesCount(20)
                    .errorsCount(0).hintsUsed(0).completionPercent(100)
                    .completed(true).abandoned(false).build();

            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(puzzleSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));
            when(puzzleSessionRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());
            when(participationRepository.existsByMedicalEventIdAndParticipantIdAndParticipantTypeAndParticipationDate(
                    any(), any(), any(), any())).thenReturn(false);
            when(participationRepository.save(any())).thenReturn(null);

            PuzzleSessionResponse response = service.submitSession(1L, 5L, request);

            assertThat(response.getScore()).isGreaterThan(0);
            assertThat(response.getCompleted()).isTrue();
        }

        @Test
        @DisplayName("Lève BusinessException si session déjà soumise")
        void submitSession_alreadySubmitted_throws() {
            openSession.setFinishedAt(LocalDateTime.now());
            PuzzleSessionSubmitRequest request = PuzzleSessionSubmitRequest.builder()
                    .patientId(4L).completed(true).abandoned(false).build();

            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(puzzleSessionRepository.findById(5L)).thenReturn(Optional.of(openSession));

            assertThatThrownBy(() -> service.submitSession(1L, 5L, request))
                    .isInstanceOf(BusinessException.class)
                    .hasMessageContaining("already been submitted");
        }

        @Test
        @DisplayName("Lève ResourceNotFoundException si session inconnue")
        void submitSession_sessionNotFound() {
            PuzzleSessionSubmitRequest request = PuzzleSessionSubmitRequest.builder()
                    .patientId(4L).completed(true).abandoned(false).build();

            when(souvenirPuzzleRepository.findById(1L)).thenReturn(Optional.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(puzzleSessionRepository.findById(99L)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> service.submitSession(1L, 99L, request))
                    .isInstanceOf(ResourceNotFoundException.class);
        }
    }

    // ── getPuzzlesByPatient ───────────────────────────────────────────────────

    @Nested
    @DisplayName("getPuzzlesByPatient")
    class GetPuzzlesByPatient {

        @Test
        @DisplayName("Retourne la liste des puzzles du patient")
        void getByPatient_returnsList() {
            when(souvenirPuzzleRepository.findByPatientIdOrderByCreatedAtDesc(4L))
                    .thenReturn(List.of(samplePuzzle));
            when(restTemplate.getForObject(anyString(), eq(SouvenirSourceSummary.class))).thenReturn(sampleSouvenir);
            when(puzzleSessionRepository.findByPuzzle_IdAndCompletedTrueOrderByScoreDescDurationSecondsAscFinishedAtAsc(any()))
                    .thenReturn(List.of());

            List<PuzzleResponse> result = service.getPuzzlesByPatient(4L);

            assertThat(result).hasSize(1);
            assertThat(result.get(0).getPatientId()).isEqualTo(4L);
        }

        @Test
        @DisplayName("Retourne liste vide si aucun puzzle")
        void getByPatient_empty() {
            when(souvenirPuzzleRepository.findByPatientIdOrderByCreatedAtDesc(99L)).thenReturn(List.of());

            List<PuzzleResponse> result = service.getPuzzlesByPatient(99L);

            assertThat(result).isEmpty();
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private PuzzleCreateRequest buildRequest(DifficultyLevel difficulty) {
        return PuzzleCreateRequest.builder()
                .souvenirEntryId(42L).patientId(4L)
                .title("Puzzle Mariage 1985").description("Photo du mariage")
                .difficulty(difficulty).timeLimitSeconds(300).maxHints(3).build();
    }
}
